// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpsjWQvmm3fuIYnxI2bZPjCZV9ZiQ9WIQ',
    appId: '1:721174157757:web:e6ebbc899e4b550bff1ad4',
    messagingSenderId: '721174157757',
    projectId: 'fire-exam-mobile',
    authDomain: 'fire-exam-mobile.firebaseapp.com',
    storageBucket: 'fire-exam-mobile.appspot.com',
    measurementId: 'G-MV0KR8S8MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDW_c8qUEACRo7aVG6nHVGTLVBRN84Vzk',
    appId: '1:721174157757:android:856b7e57cecfa2bbff1ad4',
    messagingSenderId: '721174157757',
    projectId: 'fire-exam-mobile',
    storageBucket: 'fire-exam-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrraeBEyZ2xM903DLnL1ym2PUGsJsXbI',
    appId: '1:721174157757:ios:ade8db628010f35fff1ad4',
    messagingSenderId: '721174157757',
    projectId: 'fire-exam-mobile',
    storageBucket: 'fire-exam-mobile.appspot.com',
    iosBundleId: 'com.example.segundoParcial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATrraeBEyZ2xM903DLnL1ym2PUGsJsXbI',
    appId: '1:721174157757:ios:ade8db628010f35fff1ad4',
    messagingSenderId: '721174157757',
    projectId: 'fire-exam-mobile',
    storageBucket: 'fire-exam-mobile.appspot.com',
    iosBundleId: 'com.example.segundoParcial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpsjWQvmm3fuIYnxI2bZPjCZV9ZiQ9WIQ',
    appId: '1:721174157757:web:db35240a45ba5b44ff1ad4',
    messagingSenderId: '721174157757',
    projectId: 'fire-exam-mobile',
    authDomain: 'fire-exam-mobile.firebaseapp.com',
    storageBucket: 'fire-exam-mobile.appspot.com',
    measurementId: 'G-6TEJ7SF5EY',
  );

}